-- 코드를 입력하세요
SELECT DR.DR_NAME, DR.DR_ID, DR.MCDP_CD, DATE_FORMAT(DR.HIRE_YMD, '%Y-%m-%d') AS HIRE_YMD
FROM DOCTOR DR
WHERE DR.MCDP_CD = 'CS' OR DR.MCDP_CD = 'GS'
ORDER BY DR.HIRE_YMD DESC, DR.DR_NAME ASC;